#!/usr/bin/env python3 -tt
"""
MITRE ATT&CK Technique Definitions for Elastic/Kibana Dashboards

Comprehensive mapping of all MITRE ATT&CK techniques (v18.1) with
metadata for generating Kibana dashboards.
"""

# All MITRE ATT&CK techniques organized by tactic
TECHNIQUES = {
    # Reconnaissance
    "T1595": {"name": "Active Scanning", "tactic": "Reconnaissance"},
    "T1595.001": {"name": "Scanning IP Blocks", "tactic": "Reconnaissance", "parent": "T1595"},
    "T1595.002": {"name": "Vulnerability Scanning", "tactic": "Reconnaissance", "parent": "T1595"},
    "T1595.003": {"name": "Wordlist Scanning", "tactic": "Reconnaissance", "parent": "T1595"},
    "T1592": {"name": "Gather Victim Host Information", "tactic": "Reconnaissance"},
    "T1592.001": {"name": "Hardware", "tactic": "Reconnaissance", "parent": "T1592"},
    "T1592.002": {"name": "Software", "tactic": "Reconnaissance", "parent": "T1592"},
    "T1592.003": {"name": "Firmware", "tactic": "Reconnaissance", "parent": "T1592"},
    "T1592.004": {"name": "Client Configurations", "tactic": "Reconnaissance", "parent": "T1592"},
    "T1589": {"name": "Gather Victim Identity Information", "tactic": "Reconnaissance"},
    "T1589.001": {"name": "Credentials", "tactic": "Reconnaissance", "parent": "T1589"},
    "T1589.002": {"name": "Email Addresses", "tactic": "Reconnaissance", "parent": "T1589"},
    "T1589.003": {"name": "Employee Names", "tactic": "Reconnaissance", "parent": "T1589"},
    "T1590": {"name": "Gather Victim Network Information", "tactic": "Reconnaissance"},
    "T1590.001": {"name": "Domain Properties", "tactic": "Reconnaissance", "parent": "T1590"},
    "T1590.002": {"name": "DNS", "tactic": "Reconnaissance", "parent": "T1590"},
    "T1590.003": {"name": "Network Trust Dependencies", "tactic": "Reconnaissance", "parent": "T1590"},
    "T1590.004": {"name": "Network Topology", "tactic": "Reconnaissance", "parent": "T1590"},
    "T1590.005": {"name": "IP Addresses", "tactic": "Reconnaissance", "parent": "T1590"},
    "T1590.006": {"name": "Network Security Appliances", "tactic": "Reconnaissance", "parent": "T1590"},
    "T1591": {"name": "Gather Victim Org Information", "tactic": "Reconnaissance"},
    "T1591.001": {"name": "Determine Physical Locations", "tactic": "Reconnaissance", "parent": "T1591"},
    "T1591.002": {"name": "Business Relationships", "tactic": "Reconnaissance", "parent": "T1591"},
    "T1591.003": {"name": "Identify Business Tempo", "tactic": "Reconnaissance", "parent": "T1591"},
    "T1591.004": {"name": "Identify Roles", "tactic": "Reconnaissance", "parent": "T1591"},
    "T1598": {"name": "Phishing for Information", "tactic": "Reconnaissance"},
    "T1598.001": {"name": "Spearphishing Service", "tactic": "Reconnaissance", "parent": "T1598"},
    "T1598.002": {"name": "Spearphishing Attachment", "tactic": "Reconnaissance", "parent": "T1598"},
    "T1598.003": {"name": "Spearphishing Link", "tactic": "Reconnaissance", "parent": "T1598"},
    "T1597": {"name": "Search Closed Sources", "tactic": "Reconnaissance"},
    "T1597.001": {"name": "Threat Intel Vendors", "tactic": "Reconnaissance", "parent": "T1597"},
    "T1597.002": {"name": "Purchase Technical Data", "tactic": "Reconnaissance", "parent": "T1597"},
    "T1596": {"name": "Search Open Technical Databases", "tactic": "Reconnaissance"},
    "T1596.001": {"name": "DNS/Passive DNS", "tactic": "Reconnaissance", "parent": "T1596"},
    "T1596.002": {"name": "WHOIS", "tactic": "Reconnaissance", "parent": "T1596"},
    "T1596.003": {"name": "Digital Certificates", "tactic": "Reconnaissance", "parent": "T1596"},
    "T1596.004": {"name": "CDNs", "tactic": "Reconnaissance", "parent": "T1596"},
    "T1596.005": {"name": "Scan Databases", "tactic": "Reconnaissance", "parent": "T1596"},
    "T1593": {"name": "Search Open Websites/Domains", "tactic": "Reconnaissance"},
    "T1593.001": {"name": "Social Media", "tactic": "Reconnaissance", "parent": "T1593"},
    "T1593.002": {"name": "Search Engines", "tactic": "Reconnaissance", "parent": "T1593"},
    "T1593.003": {"name": "Code Repositories", "tactic": "Reconnaissance", "parent": "T1593"},
    "T1594": {"name": "Search Victim-Owned Websites", "tactic": "Reconnaissance"},

    # Resource Development
    "T1583": {"name": "Acquire Infrastructure", "tactic": "Resource Development"},
    "T1583.001": {"name": "Domains", "tactic": "Resource Development", "parent": "T1583"},
    "T1583.002": {"name": "DNS Server", "tactic": "Resource Development", "parent": "T1583"},
    "T1583.003": {"name": "Virtual Private Server", "tactic": "Resource Development", "parent": "T1583"},
    "T1583.004": {"name": "Server", "tactic": "Resource Development", "parent": "T1583"},
    "T1583.005": {"name": "Botnet", "tactic": "Resource Development", "parent": "T1583"},
    "T1583.006": {"name": "Web Services", "tactic": "Resource Development", "parent": "T1583"},
    "T1583.007": {"name": "Serverless", "tactic": "Resource Development", "parent": "T1583"},
    "T1583.008": {"name": "Malvertising", "tactic": "Resource Development", "parent": "T1583"},
    "T1586": {"name": "Compromise Accounts", "tactic": "Resource Development"},
    "T1586.001": {"name": "Social Media Accounts", "tactic": "Resource Development", "parent": "T1586"},
    "T1586.002": {"name": "Email Accounts", "tactic": "Resource Development", "parent": "T1586"},
    "T1586.003": {"name": "Cloud Accounts", "tactic": "Resource Development", "parent": "T1586"},
    "T1584": {"name": "Compromise Infrastructure", "tactic": "Resource Development"},
    "T1584.001": {"name": "Domains", "tactic": "Resource Development", "parent": "T1584"},
    "T1584.002": {"name": "DNS Server", "tactic": "Resource Development", "parent": "T1584"},
    "T1584.003": {"name": "Virtual Private Server", "tactic": "Resource Development", "parent": "T1584"},
    "T1584.004": {"name": "Server", "tactic": "Resource Development", "parent": "T1584"},
    "T1584.005": {"name": "Botnet", "tactic": "Resource Development", "parent": "T1584"},
    "T1584.006": {"name": "Web Services", "tactic": "Resource Development", "parent": "T1584"},
    "T1584.007": {"name": "Serverless", "tactic": "Resource Development", "parent": "T1584"},
    "T1587": {"name": "Develop Capabilities", "tactic": "Resource Development"},
    "T1587.001": {"name": "Malware", "tactic": "Resource Development", "parent": "T1587"},
    "T1587.002": {"name": "Code Signing Certificates", "tactic": "Resource Development", "parent": "T1587"},
    "T1587.003": {"name": "Digital Certificates", "tactic": "Resource Development", "parent": "T1587"},
    "T1587.004": {"name": "Exploits", "tactic": "Resource Development", "parent": "T1587"},
    "T1585": {"name": "Establish Accounts", "tactic": "Resource Development"},
    "T1585.001": {"name": "Social Media Accounts", "tactic": "Resource Development", "parent": "T1585"},
    "T1585.002": {"name": "Email Accounts", "tactic": "Resource Development", "parent": "T1585"},
    "T1585.003": {"name": "Cloud Accounts", "tactic": "Resource Development", "parent": "T1585"},
    "T1588": {"name": "Obtain Capabilities", "tactic": "Resource Development"},
    "T1588.001": {"name": "Malware", "tactic": "Resource Development", "parent": "T1588"},
    "T1588.002": {"name": "Tool", "tactic": "Resource Development", "parent": "T1588"},
    "T1588.003": {"name": "Code Signing Certificates", "tactic": "Resource Development", "parent": "T1588"},
    "T1588.004": {"name": "Digital Certificates", "tactic": "Resource Development", "parent": "T1588"},
    "T1588.005": {"name": "Exploits", "tactic": "Resource Development", "parent": "T1588"},
    "T1588.006": {"name": "Vulnerabilities", "tactic": "Resource Development", "parent": "T1588"},
    "T1608": {"name": "Stage Capabilities", "tactic": "Resource Development"},
    "T1608.001": {"name": "Upload Malware", "tactic": "Resource Development", "parent": "T1608"},
    "T1608.002": {"name": "Upload Tool", "tactic": "Resource Development", "parent": "T1608"},
    "T1608.003": {"name": "Install Digital Certificate", "tactic": "Resource Development", "parent": "T1608"},
    "T1608.004": {"name": "Drive-by Target", "tactic": "Resource Development", "parent": "T1608"},
    "T1608.005": {"name": "Link Target", "tactic": "Resource Development", "parent": "T1608"},
    "T1608.006": {"name": "SEO Poisoning", "tactic": "Resource Development", "parent": "T1608"},
    "T1650": {"name": "Acquire Access", "tactic": "Resource Development"},

    # Initial Access
    "T1659": {"name": "Content Injection", "tactic": "Initial Access"},
    "T1189": {"name": "Drive-by Compromise", "tactic": "Initial Access"},
    "T1190": {"name": "Exploit Public-Facing Application", "tactic": "Initial Access"},
    "T1133": {"name": "External Remote Services", "tactic": "Initial Access"},
    "T1200": {"name": "Hardware Additions", "tactic": "Initial Access"},
    "T1566": {"name": "Phishing", "tactic": "Initial Access"},
    "T1566.001": {"name": "Spearphishing Attachment", "tactic": "Initial Access", "parent": "T1566"},
    "T1566.002": {"name": "Spearphishing Link", "tactic": "Initial Access", "parent": "T1566"},
    "T1566.003": {"name": "Spearphishing via Service", "tactic": "Initial Access", "parent": "T1566"},
    "T1566.004": {"name": "Spearphishing Voice", "tactic": "Initial Access", "parent": "T1566"},
    "T1091": {"name": "Replication Through Removable Media", "tactic": "Initial Access"},
    "T1195": {"name": "Supply Chain Compromise", "tactic": "Initial Access"},
    "T1195.001": {"name": "Compromise Software Dependencies and Development Tools", "tactic": "Initial Access", "parent": "T1195"},
    "T1195.002": {"name": "Compromise Software Supply Chain", "tactic": "Initial Access", "parent": "T1195"},
    "T1195.003": {"name": "Compromise Hardware Supply Chain", "tactic": "Initial Access", "parent": "T1195"},
    "T1199": {"name": "Trusted Relationship", "tactic": "Initial Access"},
    "T1078": {"name": "Valid Accounts", "tactic": "Initial Access"},
    "T1078.001": {"name": "Default Accounts", "tactic": "Initial Access", "parent": "T1078"},
    "T1078.002": {"name": "Domain Accounts", "tactic": "Initial Access", "parent": "T1078"},
    "T1078.003": {"name": "Local Accounts", "tactic": "Initial Access", "parent": "T1078"},
    "T1078.004": {"name": "Cloud Accounts", "tactic": "Initial Access", "parent": "T1078"},

    # Execution
    "T1651": {"name": "Cloud Administration Command", "tactic": "Execution"},
    "T1059": {"name": "Command and Scripting Interpreter", "tactic": "Execution"},
    "T1059.001": {"name": "PowerShell", "tactic": "Execution", "parent": "T1059"},
    "T1059.002": {"name": "AppleScript", "tactic": "Execution", "parent": "T1059"},
    "T1059.003": {"name": "Windows Command Shell", "tactic": "Execution", "parent": "T1059"},
    "T1059.004": {"name": "Unix Shell", "tactic": "Execution", "parent": "T1059"},
    "T1059.005": {"name": "Visual Basic", "tactic": "Execution", "parent": "T1059"},
    "T1059.006": {"name": "Python", "tactic": "Execution", "parent": "T1059"},
    "T1059.007": {"name": "JavaScript", "tactic": "Execution", "parent": "T1059"},
    "T1059.008": {"name": "Network Device CLI", "tactic": "Execution", "parent": "T1059"},
    "T1059.009": {"name": "Cloud API", "tactic": "Execution", "parent": "T1059"},
    "T1609": {"name": "Container Administration Command", "tactic": "Execution"},
    "T1610": {"name": "Deploy Container", "tactic": "Execution"},
    "T1203": {"name": "Exploitation for Client Execution", "tactic": "Execution"},
    "T1559": {"name": "Inter-Process Communication", "tactic": "Execution"},
    "T1559.001": {"name": "Component Object Model", "tactic": "Execution", "parent": "T1559"},
    "T1559.002": {"name": "Dynamic Data Exchange", "tactic": "Execution", "parent": "T1559"},
    "T1559.003": {"name": "XPC Services", "tactic": "Execution", "parent": "T1559"},
    "T1106": {"name": "Native API", "tactic": "Execution"},
    "T1053": {"name": "Scheduled Task/Job", "tactic": "Execution"},
    "T1053.002": {"name": "At", "tactic": "Execution", "parent": "T1053"},
    "T1053.003": {"name": "Cron", "tactic": "Execution", "parent": "T1053"},
    "T1053.005": {"name": "Scheduled Task", "tactic": "Execution", "parent": "T1053"},
    "T1053.006": {"name": "Systemd Timers", "tactic": "Execution", "parent": "T1053"},
    "T1053.007": {"name": "Container Orchestration Job", "tactic": "Execution", "parent": "T1053"},
    "T1129": {"name": "Shared Modules", "tactic": "Execution"},
    "T1072": {"name": "Software Deployment Tools", "tactic": "Execution"},
    "T1569": {"name": "System Services", "tactic": "Execution"},
    "T1569.001": {"name": "Launchctl", "tactic": "Execution", "parent": "T1569"},
    "T1569.002": {"name": "Service Execution", "tactic": "Execution", "parent": "T1569"},
    "T1204": {"name": "User Execution", "tactic": "Execution"},
    "T1204.001": {"name": "Malicious Link", "tactic": "Execution", "parent": "T1204"},
    "T1204.002": {"name": "Malicious File", "tactic": "Execution", "parent": "T1204"},
    "T1204.003": {"name": "Malicious Image", "tactic": "Execution", "parent": "T1204"},
    "T1047": {"name": "Windows Management Instrumentation", "tactic": "Execution"},

    # Persistence
    "T1098": {"name": "Account Manipulation", "tactic": "Persistence"},
    "T1098.001": {"name": "Additional Cloud Credentials", "tactic": "Persistence", "parent": "T1098"},
    "T1098.002": {"name": "Additional Email Delegate Permissions", "tactic": "Persistence", "parent": "T1098"},
    "T1098.003": {"name": "Additional Cloud Roles", "tactic": "Persistence", "parent": "T1098"},
    "T1098.004": {"name": "SSH Authorized Keys", "tactic": "Persistence", "parent": "T1098"},
    "T1098.005": {"name": "Device Registration", "tactic": "Persistence", "parent": "T1098"},
    "T1098.006": {"name": "Additional Container Cluster Roles", "tactic": "Persistence", "parent": "T1098"},
    "T1197": {"name": "BITS Jobs", "tactic": "Persistence"},
    "T1547": {"name": "Boot or Logon Autostart Execution", "tactic": "Persistence"},
    "T1547.001": {"name": "Registry Run Keys / Startup Folder", "tactic": "Persistence", "parent": "T1547"},
    "T1547.002": {"name": "Authentication Package", "tactic": "Persistence", "parent": "T1547"},
    "T1547.003": {"name": "Time Providers", "tactic": "Persistence", "parent": "T1547"},
    "T1547.004": {"name": "Winlogon Helper DLL", "tactic": "Persistence", "parent": "T1547"},
    "T1547.005": {"name": "Security Support Provider", "tactic": "Persistence", "parent": "T1547"},
    "T1547.006": {"name": "Kernel Modules and Extensions", "tactic": "Persistence", "parent": "T1547"},
    "T1547.007": {"name": "Re-opened Applications", "tactic": "Persistence", "parent": "T1547"},
    "T1547.008": {"name": "LSASS Driver", "tactic": "Persistence", "parent": "T1547"},
    "T1547.009": {"name": "Shortcut Modification", "tactic": "Persistence", "parent": "T1547"},
    "T1547.010": {"name": "Port Monitors", "tactic": "Persistence", "parent": "T1547"},
    "T1547.012": {"name": "Print Processors", "tactic": "Persistence", "parent": "T1547"},
    "T1547.013": {"name": "XDG Autostart Entries", "tactic": "Persistence", "parent": "T1547"},
    "T1547.014": {"name": "Active Setup", "tactic": "Persistence", "parent": "T1547"},
    "T1547.015": {"name": "Login Items", "tactic": "Persistence", "parent": "T1547"},
    "T1037": {"name": "Boot or Logon Initialization Scripts", "tactic": "Persistence"},
    "T1037.001": {"name": "Logon Script (Windows)", "tactic": "Persistence", "parent": "T1037"},
    "T1037.002": {"name": "Login Hook", "tactic": "Persistence", "parent": "T1037"},
    "T1037.003": {"name": "Network Logon Script", "tactic": "Persistence", "parent": "T1037"},
    "T1037.004": {"name": "RC Scripts", "tactic": "Persistence", "parent": "T1037"},
    "T1037.005": {"name": "Startup Items", "tactic": "Persistence", "parent": "T1037"},
    "T1176": {"name": "Browser Extensions", "tactic": "Persistence"},
    "T1554": {"name": "Compromise Client Software Binary", "tactic": "Persistence"},
    "T1136": {"name": "Create Account", "tactic": "Persistence"},
    "T1136.001": {"name": "Local Account", "tactic": "Persistence", "parent": "T1136"},
    "T1136.002": {"name": "Domain Account", "tactic": "Persistence", "parent": "T1136"},
    "T1136.003": {"name": "Cloud Account", "tactic": "Persistence", "parent": "T1136"},
    "T1543": {"name": "Create or Modify System Process", "tactic": "Persistence"},
    "T1543.001": {"name": "Launch Agent", "tactic": "Persistence", "parent": "T1543"},
    "T1543.002": {"name": "Systemd Service", "tactic": "Persistence", "parent": "T1543"},
    "T1543.003": {"name": "Windows Service", "tactic": "Persistence", "parent": "T1543"},
    "T1543.004": {"name": "Launch Daemon", "tactic": "Persistence", "parent": "T1543"},
    "T1543.005": {"name": "Container Service", "tactic": "Persistence", "parent": "T1543"},
    "T1546": {"name": "Event Triggered Execution", "tactic": "Persistence"},
    "T1546.001": {"name": "Change Default File Association", "tactic": "Persistence", "parent": "T1546"},
    "T1546.002": {"name": "Screensaver", "tactic": "Persistence", "parent": "T1546"},
    "T1546.003": {"name": "Windows Management Instrumentation Event Subscription", "tactic": "Persistence", "parent": "T1546"},
    "T1546.004": {"name": "Unix Shell Configuration Modification", "tactic": "Persistence", "parent": "T1546"},
    "T1546.005": {"name": "Trap", "tactic": "Persistence", "parent": "T1546"},
    "T1546.006": {"name": "LC_LOAD_DYLIB Addition", "tactic": "Persistence", "parent": "T1546"},
    "T1546.007": {"name": "Netsh Helper DLL", "tactic": "Persistence", "parent": "T1546"},
    "T1546.008": {"name": "Accessibility Features", "tactic": "Persistence", "parent": "T1546"},
    "T1546.009": {"name": "AppCert DLLs", "tactic": "Persistence", "parent": "T1546"},
    "T1546.010": {"name": "AppInit DLLs", "tactic": "Persistence", "parent": "T1546"},
    "T1546.011": {"name": "Application Shimming", "tactic": "Persistence", "parent": "T1546"},
    "T1546.012": {"name": "Image File Execution Options Injection", "tactic": "Persistence", "parent": "T1546"},
    "T1546.013": {"name": "PowerShell Profile", "tactic": "Persistence", "parent": "T1546"},
    "T1546.014": {"name": "Emond", "tactic": "Persistence", "parent": "T1546"},
    "T1546.015": {"name": "Component Object Model Hijacking", "tactic": "Persistence", "parent": "T1546"},
    "T1546.016": {"name": "Installer Packages", "tactic": "Persistence", "parent": "T1546"},
    "T1574": {"name": "Hijack Execution Flow", "tactic": "Persistence"},
    "T1574.001": {"name": "DLL Search Order Hijacking", "tactic": "Persistence", "parent": "T1574"},
    "T1574.002": {"name": "DLL Side-Loading", "tactic": "Persistence", "parent": "T1574"},
    "T1574.004": {"name": "Dylib Hijacking", "tactic": "Persistence", "parent": "T1574"},
    "T1574.005": {"name": "Executable Installer File Permissions Weakness", "tactic": "Persistence", "parent": "T1574"},
    "T1574.006": {"name": "Dynamic Linker Hijacking", "tactic": "Persistence", "parent": "T1574"},
    "T1574.007": {"name": "Path Interception by PATH Environment Variable", "tactic": "Persistence", "parent": "T1574"},
    "T1574.008": {"name": "Path Interception by Search Order Hijacking", "tactic": "Persistence", "parent": "T1574"},
    "T1574.009": {"name": "Path Interception by Unquoted Path", "tactic": "Persistence", "parent": "T1574"},
    "T1574.010": {"name": "Services File Permissions Weakness", "tactic": "Persistence", "parent": "T1574"},
    "T1574.011": {"name": "Services Registry Permissions Weakness", "tactic": "Persistence", "parent": "T1574"},
    "T1574.012": {"name": "COR_PROFILER", "tactic": "Persistence", "parent": "T1574"},
    "T1574.013": {"name": "KernelCallbackTable", "tactic": "Persistence", "parent": "T1574"},
    "T1574.014": {"name": "AppDomainManager", "tactic": "Persistence", "parent": "T1574"},
    "T1525": {"name": "Implant Internal Image", "tactic": "Persistence"},
    "T1556": {"name": "Modify Authentication Process", "tactic": "Persistence"},
    "T1556.001": {"name": "Domain Controller Authentication", "tactic": "Persistence", "parent": "T1556"},
    "T1556.002": {"name": "Password Filter DLL", "tactic": "Persistence", "parent": "T1556"},
    "T1556.003": {"name": "Pluggable Authentication Modules", "tactic": "Persistence", "parent": "T1556"},
    "T1556.004": {"name": "Network Device Authentication", "tactic": "Persistence", "parent": "T1556"},
    "T1556.005": {"name": "Reversible Encryption", "tactic": "Persistence", "parent": "T1556"},
    "T1556.006": {"name": "Multi-Factor Authentication", "tactic": "Persistence", "parent": "T1556"},
    "T1556.007": {"name": "Hybrid Identity", "tactic": "Persistence", "parent": "T1556"},
    "T1556.008": {"name": "Network Provider DLL", "tactic": "Persistence", "parent": "T1556"},
    "T1137": {"name": "Office Application Startup", "tactic": "Persistence"},
    "T1137.001": {"name": "Office Template Macros", "tactic": "Persistence", "parent": "T1137"},
    "T1137.002": {"name": "Office Test", "tactic": "Persistence", "parent": "T1137"},
    "T1137.003": {"name": "Outlook Forms", "tactic": "Persistence", "parent": "T1137"},
    "T1137.004": {"name": "Outlook Home Page", "tactic": "Persistence", "parent": "T1137"},
    "T1137.005": {"name": "Outlook Rules", "tactic": "Persistence", "parent": "T1137"},
    "T1137.006": {"name": "Add-ins", "tactic": "Persistence", "parent": "T1137"},
    "T1653": {"name": "Power Settings", "tactic": "Persistence"},
    "T1542": {"name": "Pre-OS Boot", "tactic": "Persistence"},
    "T1542.001": {"name": "System Firmware", "tactic": "Persistence", "parent": "T1542"},
    "T1542.002": {"name": "Component Firmware", "tactic": "Persistence", "parent": "T1542"},
    "T1542.003": {"name": "Bootkit", "tactic": "Persistence", "parent": "T1542"},
    "T1542.004": {"name": "ROMMONkit", "tactic": "Persistence", "parent": "T1542"},
    "T1542.005": {"name": "TFTP Boot", "tactic": "Persistence", "parent": "T1542"},
    "T1505": {"name": "Server Software Component", "tactic": "Persistence"},
    "T1505.001": {"name": "SQL Stored Procedures", "tactic": "Persistence", "parent": "T1505"},
    "T1505.002": {"name": "Transport Agent", "tactic": "Persistence", "parent": "T1505"},
    "T1505.003": {"name": "Web Shell", "tactic": "Persistence", "parent": "T1505"},
    "T1505.004": {"name": "IIS Components", "tactic": "Persistence", "parent": "T1505"},
    "T1505.005": {"name": "Terminal Services DLL", "tactic": "Persistence", "parent": "T1505"},
    "T1205": {"name": "Traffic Signaling", "tactic": "Persistence"},
    "T1205.001": {"name": "Port Knocking", "tactic": "Persistence", "parent": "T1205"},
    "T1205.002": {"name": "Socket Filters", "tactic": "Persistence", "parent": "T1205"},

    # Privilege Escalation
    "T1548": {"name": "Abuse Elevation Control Mechanism", "tactic": "Privilege Escalation"},
    "T1548.001": {"name": "Setuid and Setgid", "tactic": "Privilege Escalation", "parent": "T1548"},
    "T1548.002": {"name": "Bypass User Account Control", "tactic": "Privilege Escalation", "parent": "T1548"},
    "T1548.003": {"name": "Sudo and Sudo Caching", "tactic": "Privilege Escalation", "parent": "T1548"},
    "T1548.004": {"name": "Elevated Execution with Prompt", "tactic": "Privilege Escalation", "parent": "T1548"},
    "T1548.005": {"name": "Temporary Elevated Cloud Access", "tactic": "Privilege Escalation", "parent": "T1548"},
    "T1134": {"name": "Access Token Manipulation", "tactic": "Privilege Escalation"},
    "T1134.001": {"name": "Token Impersonation/Theft", "tactic": "Privilege Escalation", "parent": "T1134"},
    "T1134.002": {"name": "Create Process with Token", "tactic": "Privilege Escalation", "parent": "T1134"},
    "T1134.003": {"name": "Make and Impersonate Token", "tactic": "Privilege Escalation", "parent": "T1134"},
    "T1134.004": {"name": "Parent PID Spoofing", "tactic": "Privilege Escalation", "parent": "T1134"},
    "T1134.005": {"name": "SID-History Injection", "tactic": "Privilege Escalation", "parent": "T1134"},
    "T1484": {"name": "Domain Policy Modification", "tactic": "Privilege Escalation"},
    "T1484.001": {"name": "Group Policy Modification", "tactic": "Privilege Escalation", "parent": "T1484"},
    "T1484.002": {"name": "Domain Trust Modification", "tactic": "Privilege Escalation", "parent": "T1484"},
    "T1611": {"name": "Escape to Host", "tactic": "Privilege Escalation"},
    "T1068": {"name": "Exploitation for Privilege Escalation", "tactic": "Privilege Escalation"},
    "T1055": {"name": "Process Injection", "tactic": "Privilege Escalation"},
    "T1055.001": {"name": "Dynamic-link Library Injection", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.002": {"name": "Portable Executable Injection", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.003": {"name": "Thread Execution Hijacking", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.004": {"name": "Asynchronous Procedure Call", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.005": {"name": "Thread Local Storage", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.008": {"name": "Ptrace System Calls", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.009": {"name": "Proc Memory", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.011": {"name": "Extra Window Memory Injection", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.012": {"name": "Process Hollowing", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.013": {"name": "Process Doppelganging", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.014": {"name": "VDSO Hijacking", "tactic": "Privilege Escalation", "parent": "T1055"},
    "T1055.015": {"name": "ListPlanting", "tactic": "Privilege Escalation", "parent": "T1055"},

    # Defense Evasion
    "T1612": {"name": "Build Image on Host", "tactic": "Defense Evasion"},
    "T1622": {"name": "Debugger Evasion", "tactic": "Defense Evasion"},
    "T1140": {"name": "Deobfuscate/Decode Files or Information", "tactic": "Defense Evasion"},
    "T1006": {"name": "Direct Volume Access", "tactic": "Defense Evasion"},
    "T1480": {"name": "Execution Guardrails", "tactic": "Defense Evasion"},
    "T1480.001": {"name": "Environmental Keying", "tactic": "Defense Evasion", "parent": "T1480"},
    "T1211": {"name": "Exploitation for Defense Evasion", "tactic": "Defense Evasion"},
    "T1222": {"name": "File and Directory Permissions Modification", "tactic": "Defense Evasion"},
    "T1222.001": {"name": "Windows File and Directory Permissions Modification", "tactic": "Defense Evasion", "parent": "T1222"},
    "T1222.002": {"name": "Linux and Mac File and Directory Permissions Modification", "tactic": "Defense Evasion", "parent": "T1222"},
    "T1564": {"name": "Hide Artifacts", "tactic": "Defense Evasion"},
    "T1564.001": {"name": "Hidden Files and Directories", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.002": {"name": "Hidden Users", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.003": {"name": "Hidden Window", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.004": {"name": "NTFS File Attributes", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.005": {"name": "Hidden File System", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.006": {"name": "Run Virtual Instance", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.007": {"name": "VBA Stomping", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.008": {"name": "Email Hiding Rules", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.009": {"name": "Resource Forking", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.010": {"name": "Process Argument Spoofing", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1564.011": {"name": "Ignore Process Interrupts", "tactic": "Defense Evasion", "parent": "T1564"},
    "T1562": {"name": "Impair Defenses", "tactic": "Defense Evasion"},
    "T1562.001": {"name": "Disable or Modify Tools", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.002": {"name": "Disable Windows Event Logging", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.003": {"name": "Impair Command History Logging", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.004": {"name": "Disable or Modify System Firewall", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.006": {"name": "Indicator Blocking", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.007": {"name": "Disable or Modify Cloud Firewall", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.008": {"name": "Disable or Modify Cloud Logs", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.009": {"name": "Safe Mode Boot", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.010": {"name": "Downgrade Attack", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.011": {"name": "Spoof Security Alerting", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1562.012": {"name": "Disable or Modify Linux Audit System", "tactic": "Defense Evasion", "parent": "T1562"},
    "T1656": {"name": "Impersonation", "tactic": "Defense Evasion"},
    "T1070": {"name": "Indicator Removal", "tactic": "Defense Evasion"},
    "T1070.001": {"name": "Clear Windows Event Logs", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1070.002": {"name": "Clear Linux or Mac System Logs", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1070.003": {"name": "Clear Command History", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1070.004": {"name": "File Deletion", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1070.005": {"name": "Network Share Connection Removal", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1070.006": {"name": "Timestomp", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1070.007": {"name": "Clear Network Connection History and Configurations", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1070.008": {"name": "Clear Mailbox Data", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1070.009": {"name": "Clear Persistence", "tactic": "Defense Evasion", "parent": "T1070"},
    "T1202": {"name": "Indirect Command Execution", "tactic": "Defense Evasion"},
    "T1036": {"name": "Masquerading", "tactic": "Defense Evasion"},
    "T1036.001": {"name": "Invalid Code Signature", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1036.002": {"name": "Right-to-Left Override", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1036.003": {"name": "Rename System Utilities", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1036.004": {"name": "Masquerade Task or Service", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1036.005": {"name": "Match Legitimate Name or Location", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1036.006": {"name": "Space after Filename", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1036.007": {"name": "Double File Extension", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1036.008": {"name": "Masquerade File Type", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1036.009": {"name": "Break Process Trees", "tactic": "Defense Evasion", "parent": "T1036"},
    "T1578": {"name": "Modify Cloud Compute Infrastructure", "tactic": "Defense Evasion"},
    "T1578.001": {"name": "Create Snapshot", "tactic": "Defense Evasion", "parent": "T1578"},
    "T1578.002": {"name": "Create Cloud Instance", "tactic": "Defense Evasion", "parent": "T1578"},
    "T1578.003": {"name": "Delete Cloud Instance", "tactic": "Defense Evasion", "parent": "T1578"},
    "T1578.004": {"name": "Revert Cloud Instance", "tactic": "Defense Evasion", "parent": "T1578"},
    "T1578.005": {"name": "Modify Cloud Compute Configurations", "tactic": "Defense Evasion", "parent": "T1578"},
    "T1112": {"name": "Modify Registry", "tactic": "Defense Evasion"},
    "T1601": {"name": "Modify System Image", "tactic": "Defense Evasion"},
    "T1601.001": {"name": "Patch System Image", "tactic": "Defense Evasion", "parent": "T1601"},
    "T1601.002": {"name": "Downgrade System Image", "tactic": "Defense Evasion", "parent": "T1601"},
    "T1599": {"name": "Network Boundary Bridging", "tactic": "Defense Evasion"},
    "T1599.001": {"name": "Network Address Translation Traversal", "tactic": "Defense Evasion", "parent": "T1599"},
    "T1027": {"name": "Obfuscated Files or Information", "tactic": "Defense Evasion"},
    "T1027.001": {"name": "Binary Padding", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.002": {"name": "Software Packing", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.003": {"name": "Steganography", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.004": {"name": "Compile After Delivery", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.005": {"name": "Indicator Removal from Tools", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.006": {"name": "HTML Smuggling", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.007": {"name": "Dynamic API Resolution", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.008": {"name": "Stripped Payloads", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.009": {"name": "Embedded Payloads", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.010": {"name": "Command Obfuscation", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.011": {"name": "Fileless Storage", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1027.012": {"name": "LNK Icon Smuggling", "tactic": "Defense Evasion", "parent": "T1027"},
    "T1647": {"name": "Plist File Modification", "tactic": "Defense Evasion"},
    "T1620": {"name": "Reflective Code Loading", "tactic": "Defense Evasion"},
    "T1207": {"name": "Rogue Domain Controller", "tactic": "Defense Evasion"},
    "T1014": {"name": "Rootkit", "tactic": "Defense Evasion"},
    "T1218": {"name": "System Binary Proxy Execution", "tactic": "Defense Evasion"},
    "T1218.001": {"name": "Compiled HTML File", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.002": {"name": "Control Panel", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.003": {"name": "CMSTP", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.004": {"name": "InstallUtil", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.005": {"name": "Mshta", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.007": {"name": "Msiexec", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.008": {"name": "Odbcconf", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.009": {"name": "Regsvcs/Regasm", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.010": {"name": "Regsvr32", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.011": {"name": "Rundll32", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.012": {"name": "Verclsid", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.013": {"name": "Mavinject", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1218.014": {"name": "MMC", "tactic": "Defense Evasion", "parent": "T1218"},
    "T1216": {"name": "System Script Proxy Execution", "tactic": "Defense Evasion"},
    "T1216.001": {"name": "PubPrn", "tactic": "Defense Evasion", "parent": "T1216"},
    "T1216.002": {"name": "SyncAppvPublishingServer", "tactic": "Defense Evasion", "parent": "T1216"},
    "T1553": {"name": "Subvert Trust Controls", "tactic": "Defense Evasion"},
    "T1553.001": {"name": "Gatekeeper Bypass", "tactic": "Defense Evasion", "parent": "T1553"},
    "T1553.002": {"name": "Code Signing", "tactic": "Defense Evasion", "parent": "T1553"},
    "T1553.003": {"name": "SIP and Trust Provider Hijacking", "tactic": "Defense Evasion", "parent": "T1553"},
    "T1553.004": {"name": "Install Root Certificate", "tactic": "Defense Evasion", "parent": "T1553"},
    "T1553.005": {"name": "Mark-of-the-Web Bypass", "tactic": "Defense Evasion", "parent": "T1553"},
    "T1553.006": {"name": "Code Signing Policy Modification", "tactic": "Defense Evasion", "parent": "T1553"},
    "T1221": {"name": "Template Injection", "tactic": "Defense Evasion"},
    "T1127": {"name": "Trusted Developer Utilities Proxy Execution", "tactic": "Defense Evasion"},
    "T1127.001": {"name": "MSBuild", "tactic": "Defense Evasion", "parent": "T1127"},
    "T1535": {"name": "Unused/Unsupported Cloud Regions", "tactic": "Defense Evasion"},
    "T1550": {"name": "Use Alternate Authentication Material", "tactic": "Defense Evasion"},
    "T1550.001": {"name": "Application Access Token", "tactic": "Defense Evasion", "parent": "T1550"},
    "T1550.002": {"name": "Pass the Hash", "tactic": "Defense Evasion", "parent": "T1550"},
    "T1550.003": {"name": "Pass the Ticket", "tactic": "Defense Evasion", "parent": "T1550"},
    "T1550.004": {"name": "Web Session Cookie", "tactic": "Defense Evasion", "parent": "T1550"},
    "T1497": {"name": "Virtualization/Sandbox Evasion", "tactic": "Defense Evasion"},
    "T1497.001": {"name": "System Checks", "tactic": "Defense Evasion", "parent": "T1497"},
    "T1497.002": {"name": "User Activity Based Checks", "tactic": "Defense Evasion", "parent": "T1497"},
    "T1497.003": {"name": "Time Based Evasion", "tactic": "Defense Evasion", "parent": "T1497"},
    "T1600": {"name": "Weaken Encryption", "tactic": "Defense Evasion"},
    "T1600.001": {"name": "Reduce Key Space", "tactic": "Defense Evasion", "parent": "T1600"},
    "T1600.002": {"name": "Disable Crypto Hardware", "tactic": "Defense Evasion", "parent": "T1600"},
    "T1220": {"name": "XSL Script Processing", "tactic": "Defense Evasion"},

    # Credential Access
    "T1557": {"name": "Adversary-in-the-Middle", "tactic": "Credential Access"},
    "T1557.001": {"name": "LLMNR/NBT-NS Poisoning and SMB Relay", "tactic": "Credential Access", "parent": "T1557"},
    "T1557.002": {"name": "ARP Cache Poisoning", "tactic": "Credential Access", "parent": "T1557"},
    "T1557.003": {"name": "DHCP Spoofing", "tactic": "Credential Access", "parent": "T1557"},
    "T1110": {"name": "Brute Force", "tactic": "Credential Access"},
    "T1110.001": {"name": "Password Guessing", "tactic": "Credential Access", "parent": "T1110"},
    "T1110.002": {"name": "Password Cracking", "tactic": "Credential Access", "parent": "T1110"},
    "T1110.003": {"name": "Password Spraying", "tactic": "Credential Access", "parent": "T1110"},
    "T1110.004": {"name": "Credential Stuffing", "tactic": "Credential Access", "parent": "T1110"},
    "T1555": {"name": "Credentials from Password Stores", "tactic": "Credential Access"},
    "T1555.001": {"name": "Keychain", "tactic": "Credential Access", "parent": "T1555"},
    "T1555.002": {"name": "Securityd Memory", "tactic": "Credential Access", "parent": "T1555"},
    "T1555.003": {"name": "Credentials from Web Browsers", "tactic": "Credential Access", "parent": "T1555"},
    "T1555.004": {"name": "Windows Credential Manager", "tactic": "Credential Access", "parent": "T1555"},
    "T1555.005": {"name": "Password Managers", "tactic": "Credential Access", "parent": "T1555"},
    "T1555.006": {"name": "Cloud Secrets Management Stores", "tactic": "Credential Access", "parent": "T1555"},
    "T1212": {"name": "Exploitation for Credential Access", "tactic": "Credential Access"},
    "T1187": {"name": "Forced Authentication", "tactic": "Credential Access"},
    "T1606": {"name": "Forge Web Credentials", "tactic": "Credential Access"},
    "T1606.001": {"name": "Web Cookies", "tactic": "Credential Access", "parent": "T1606"},
    "T1606.002": {"name": "SAML Tokens", "tactic": "Credential Access", "parent": "T1606"},
    "T1056": {"name": "Input Capture", "tactic": "Credential Access"},
    "T1056.001": {"name": "Keylogging", "tactic": "Credential Access", "parent": "T1056"},
    "T1056.002": {"name": "GUI Input Capture", "tactic": "Credential Access", "parent": "T1056"},
    "T1056.003": {"name": "Web Portal Capture", "tactic": "Credential Access", "parent": "T1056"},
    "T1056.004": {"name": "Credential API Hooking", "tactic": "Credential Access", "parent": "T1056"},
    "T1040": {"name": "Network Sniffing", "tactic": "Credential Access"},
    "T1003": {"name": "OS Credential Dumping", "tactic": "Credential Access"},
    "T1003.001": {"name": "LSASS Memory", "tactic": "Credential Access", "parent": "T1003"},
    "T1003.002": {"name": "Security Account Manager", "tactic": "Credential Access", "parent": "T1003"},
    "T1003.003": {"name": "NTDS", "tactic": "Credential Access", "parent": "T1003"},
    "T1003.004": {"name": "LSA Secrets", "tactic": "Credential Access", "parent": "T1003"},
    "T1003.005": {"name": "Cached Domain Credentials", "tactic": "Credential Access", "parent": "T1003"},
    "T1003.006": {"name": "DCSync", "tactic": "Credential Access", "parent": "T1003"},
    "T1003.007": {"name": "Proc Filesystem", "tactic": "Credential Access", "parent": "T1003"},
    "T1003.008": {"name": "/etc/passwd and /etc/shadow", "tactic": "Credential Access", "parent": "T1003"},
    "T1528": {"name": "Steal Application Access Token", "tactic": "Credential Access"},
    "T1649": {"name": "Steal or Forge Authentication Certificates", "tactic": "Credential Access"},
    "T1539": {"name": "Steal Web Session Cookie", "tactic": "Credential Access"},
    "T1111": {"name": "Multi-Factor Authentication Interception", "tactic": "Credential Access"},
    "T1621": {"name": "Multi-Factor Authentication Request Generation", "tactic": "Credential Access"},
    "T1552": {"name": "Unsecured Credentials", "tactic": "Credential Access"},
    "T1552.001": {"name": "Credentials In Files", "tactic": "Credential Access", "parent": "T1552"},
    "T1552.002": {"name": "Credentials in Registry", "tactic": "Credential Access", "parent": "T1552"},
    "T1552.003": {"name": "Bash History", "tactic": "Credential Access", "parent": "T1552"},
    "T1552.004": {"name": "Private Keys", "tactic": "Credential Access", "parent": "T1552"},
    "T1552.005": {"name": "Cloud Instance Metadata API", "tactic": "Credential Access", "parent": "T1552"},
    "T1552.006": {"name": "Group Policy Preferences", "tactic": "Credential Access", "parent": "T1552"},
    "T1552.007": {"name": "Container API", "tactic": "Credential Access", "parent": "T1552"},
    "T1552.008": {"name": "Chat Messages", "tactic": "Credential Access", "parent": "T1552"},

    # Discovery
    "T1087": {"name": "Account Discovery", "tactic": "Discovery"},
    "T1087.001": {"name": "Local Account", "tactic": "Discovery", "parent": "T1087"},
    "T1087.002": {"name": "Domain Account", "tactic": "Discovery", "parent": "T1087"},
    "T1087.003": {"name": "Email Account", "tactic": "Discovery", "parent": "T1087"},
    "T1087.004": {"name": "Cloud Account", "tactic": "Discovery", "parent": "T1087"},
    "T1010": {"name": "Application Window Discovery", "tactic": "Discovery"},
    "T1217": {"name": "Browser Information Discovery", "tactic": "Discovery"},
    "T1580": {"name": "Cloud Infrastructure Discovery", "tactic": "Discovery"},
    "T1538": {"name": "Cloud Service Dashboard", "tactic": "Discovery"},
    "T1526": {"name": "Cloud Service Discovery", "tactic": "Discovery"},
    "T1613": {"name": "Container and Resource Discovery", "tactic": "Discovery"},
    "T1652": {"name": "Device Driver Discovery", "tactic": "Discovery"},
    "T1482": {"name": "Domain Trust Discovery", "tactic": "Discovery"},
    "T1083": {"name": "File and Directory Discovery", "tactic": "Discovery"},
    "T1615": {"name": "Group Policy Discovery", "tactic": "Discovery"},
    "T1654": {"name": "Log Enumeration", "tactic": "Discovery"},
    "T1046": {"name": "Network Service Discovery", "tactic": "Discovery"},
    "T1135": {"name": "Network Share Discovery", "tactic": "Discovery"},
    "T1201": {"name": "Password Policy Discovery", "tactic": "Discovery"},
    "T1120": {"name": "Peripheral Device Discovery", "tactic": "Discovery"},
    "T1069": {"name": "Permission Groups Discovery", "tactic": "Discovery"},
    "T1069.001": {"name": "Local Groups", "tactic": "Discovery", "parent": "T1069"},
    "T1069.002": {"name": "Domain Groups", "tactic": "Discovery", "parent": "T1069"},
    "T1069.003": {"name": "Cloud Groups", "tactic": "Discovery", "parent": "T1069"},
    "T1057": {"name": "Process Discovery", "tactic": "Discovery"},
    "T1012": {"name": "Query Registry", "tactic": "Discovery"},
    "T1018": {"name": "Remote System Discovery", "tactic": "Discovery"},
    "T1518": {"name": "Software Discovery", "tactic": "Discovery"},
    "T1518.001": {"name": "Security Software Discovery", "tactic": "Discovery", "parent": "T1518"},
    "T1082": {"name": "System Information Discovery", "tactic": "Discovery"},
    "T1614": {"name": "System Location Discovery", "tactic": "Discovery"},
    "T1614.001": {"name": "System Language Discovery", "tactic": "Discovery", "parent": "T1614"},
    "T1016": {"name": "System Network Configuration Discovery", "tactic": "Discovery"},
    "T1016.001": {"name": "Internet Connection Discovery", "tactic": "Discovery", "parent": "T1016"},
    "T1016.002": {"name": "Wi-Fi Discovery", "tactic": "Discovery", "parent": "T1016"},
    "T1049": {"name": "System Network Connections Discovery", "tactic": "Discovery"},
    "T1033": {"name": "System Owner/User Discovery", "tactic": "Discovery"},
    "T1007": {"name": "System Service Discovery", "tactic": "Discovery"},
    "T1124": {"name": "System Time Discovery", "tactic": "Discovery"},

    # Lateral Movement
    "T1210": {"name": "Exploitation of Remote Services", "tactic": "Lateral Movement"},
    "T1534": {"name": "Internal Spearphishing", "tactic": "Lateral Movement"},
    "T1570": {"name": "Lateral Tool Transfer", "tactic": "Lateral Movement"},
    "T1563": {"name": "Remote Service Session Hijacking", "tactic": "Lateral Movement"},
    "T1563.001": {"name": "SSH Hijacking", "tactic": "Lateral Movement", "parent": "T1563"},
    "T1563.002": {"name": "RDP Hijacking", "tactic": "Lateral Movement", "parent": "T1563"},
    "T1021": {"name": "Remote Services", "tactic": "Lateral Movement"},
    "T1021.001": {"name": "Remote Desktop Protocol", "tactic": "Lateral Movement", "parent": "T1021"},
    "T1021.002": {"name": "SMB/Windows Admin Shares", "tactic": "Lateral Movement", "parent": "T1021"},
    "T1021.003": {"name": "Distributed Component Object Model", "tactic": "Lateral Movement", "parent": "T1021"},
    "T1021.004": {"name": "SSH", "tactic": "Lateral Movement", "parent": "T1021"},
    "T1021.005": {"name": "VNC", "tactic": "Lateral Movement", "parent": "T1021"},
    "T1021.006": {"name": "Windows Remote Management", "tactic": "Lateral Movement", "parent": "T1021"},
    "T1021.007": {"name": "Cloud Services", "tactic": "Lateral Movement", "parent": "T1021"},
    "T1021.008": {"name": "Direct Cloud VM Connections", "tactic": "Lateral Movement", "parent": "T1021"},
    "T1080": {"name": "Taint Shared Content", "tactic": "Lateral Movement"},

    # Collection
    "T1560": {"name": "Archive Collected Data", "tactic": "Collection"},
    "T1560.001": {"name": "Archive via Utility", "tactic": "Collection", "parent": "T1560"},
    "T1560.002": {"name": "Archive via Library", "tactic": "Collection", "parent": "T1560"},
    "T1560.003": {"name": "Archive via Custom Method", "tactic": "Collection", "parent": "T1560"},
    "T1123": {"name": "Audio Capture", "tactic": "Collection"},
    "T1119": {"name": "Automated Collection", "tactic": "Collection"},
    "T1115": {"name": "Clipboard Data", "tactic": "Collection"},
    "T1530": {"name": "Data from Cloud Storage", "tactic": "Collection"},
    "T1602": {"name": "Data from Configuration Repository", "tactic": "Collection"},
    "T1602.001": {"name": "SNMP (MIB Dump)", "tactic": "Collection", "parent": "T1602"},
    "T1602.002": {"name": "Network Device Configuration Dump", "tactic": "Collection", "parent": "T1602"},
    "T1213": {"name": "Data from Information Repositories", "tactic": "Collection"},
    "T1213.001": {"name": "Confluence", "tactic": "Collection", "parent": "T1213"},
    "T1213.002": {"name": "Sharepoint", "tactic": "Collection", "parent": "T1213"},
    "T1213.003": {"name": "Code Repositories", "tactic": "Collection", "parent": "T1213"},
    "T1005": {"name": "Data from Local System", "tactic": "Collection"},
    "T1039": {"name": "Data from Network Shared Drive", "tactic": "Collection"},
    "T1025": {"name": "Data from Removable Media", "tactic": "Collection"},
    "T1074": {"name": "Data Staged", "tactic": "Collection"},
    "T1074.001": {"name": "Local Data Staging", "tactic": "Collection", "parent": "T1074"},
    "T1074.002": {"name": "Remote Data Staging", "tactic": "Collection", "parent": "T1074"},
    "T1114": {"name": "Email Collection", "tactic": "Collection"},
    "T1114.001": {"name": "Local Email Collection", "tactic": "Collection", "parent": "T1114"},
    "T1114.002": {"name": "Remote Email Collection", "tactic": "Collection", "parent": "T1114"},
    "T1114.003": {"name": "Email Forwarding Rule", "tactic": "Collection", "parent": "T1114"},
    "T1185": {"name": "Browser Session Hijacking", "tactic": "Collection"},
    "T1113": {"name": "Screen Capture", "tactic": "Collection"},
    "T1125": {"name": "Video Capture", "tactic": "Collection"},

    # Command and Control
    "T1071": {"name": "Application Layer Protocol", "tactic": "Command and Control"},
    "T1071.001": {"name": "Web Protocols", "tactic": "Command and Control", "parent": "T1071"},
    "T1071.002": {"name": "File Transfer Protocols", "tactic": "Command and Control", "parent": "T1071"},
    "T1071.003": {"name": "Mail Protocols", "tactic": "Command and Control", "parent": "T1071"},
    "T1071.004": {"name": "DNS", "tactic": "Command and Control", "parent": "T1071"},
    "T1092": {"name": "Communication Through Removable Media", "tactic": "Command and Control"},
    "T1132": {"name": "Data Encoding", "tactic": "Command and Control"},
    "T1132.001": {"name": "Standard Encoding", "tactic": "Command and Control", "parent": "T1132"},
    "T1132.002": {"name": "Non-Standard Encoding", "tactic": "Command and Control", "parent": "T1132"},
    "T1001": {"name": "Data Obfuscation", "tactic": "Command and Control"},
    "T1001.001": {"name": "Junk Data", "tactic": "Command and Control", "parent": "T1001"},
    "T1001.002": {"name": "Steganography", "tactic": "Command and Control", "parent": "T1001"},
    "T1001.003": {"name": "Protocol Impersonation", "tactic": "Command and Control", "parent": "T1001"},
    "T1568": {"name": "Dynamic Resolution", "tactic": "Command and Control"},
    "T1568.001": {"name": "Fast Flux DNS", "tactic": "Command and Control", "parent": "T1568"},
    "T1568.002": {"name": "Domain Generation Algorithms", "tactic": "Command and Control", "parent": "T1568"},
    "T1568.003": {"name": "DNS Calculation", "tactic": "Command and Control", "parent": "T1568"},
    "T1573": {"name": "Encrypted Channel", "tactic": "Command and Control"},
    "T1573.001": {"name": "Symmetric Cryptography", "tactic": "Command and Control", "parent": "T1573"},
    "T1573.002": {"name": "Asymmetric Cryptography", "tactic": "Command and Control", "parent": "T1573"},
    "T1008": {"name": "Fallback Channels", "tactic": "Command and Control"},
    "T1105": {"name": "Ingress Tool Transfer", "tactic": "Command and Control"},
    "T1104": {"name": "Multi-Stage Channels", "tactic": "Command and Control"},
    "T1095": {"name": "Non-Application Layer Protocol", "tactic": "Command and Control"},
    "T1571": {"name": "Non-Standard Port", "tactic": "Command and Control"},
    "T1572": {"name": "Protocol Tunneling", "tactic": "Command and Control"},
    "T1090": {"name": "Proxy", "tactic": "Command and Control"},
    "T1090.001": {"name": "Internal Proxy", "tactic": "Command and Control", "parent": "T1090"},
    "T1090.002": {"name": "External Proxy", "tactic": "Command and Control", "parent": "T1090"},
    "T1090.003": {"name": "Multi-hop Proxy", "tactic": "Command and Control", "parent": "T1090"},
    "T1090.004": {"name": "Domain Fronting", "tactic": "Command and Control", "parent": "T1090"},
    "T1219": {"name": "Remote Access Software", "tactic": "Command and Control"},
    "T1102": {"name": "Web Service", "tactic": "Command and Control"},
    "T1102.001": {"name": "Dead Drop Resolver", "tactic": "Command and Control", "parent": "T1102"},
    "T1102.002": {"name": "Bidirectional Communication", "tactic": "Command and Control", "parent": "T1102"},
    "T1102.003": {"name": "One-Way Communication", "tactic": "Command and Control", "parent": "T1102"},

    # Exfiltration
    "T1020": {"name": "Automated Exfiltration", "tactic": "Exfiltration"},
    "T1020.001": {"name": "Traffic Duplication", "tactic": "Exfiltration", "parent": "T1020"},
    "T1030": {"name": "Data Transfer Size Limits", "tactic": "Exfiltration"},
    "T1048": {"name": "Exfiltration Over Alternative Protocol", "tactic": "Exfiltration"},
    "T1048.001": {"name": "Exfiltration Over Symmetric Encrypted Non-C2 Protocol", "tactic": "Exfiltration", "parent": "T1048"},
    "T1048.002": {"name": "Exfiltration Over Asymmetric Encrypted Non-C2 Protocol", "tactic": "Exfiltration", "parent": "T1048"},
    "T1048.003": {"name": "Exfiltration Over Unencrypted Non-C2 Protocol", "tactic": "Exfiltration", "parent": "T1048"},
    "T1041": {"name": "Exfiltration Over C2 Channel", "tactic": "Exfiltration"},
    "T1011": {"name": "Exfiltration Over Other Network Medium", "tactic": "Exfiltration"},
    "T1011.001": {"name": "Exfiltration Over Bluetooth", "tactic": "Exfiltration", "parent": "T1011"},
    "T1052": {"name": "Exfiltration Over Physical Medium", "tactic": "Exfiltration"},
    "T1052.001": {"name": "Exfiltration over USB", "tactic": "Exfiltration", "parent": "T1052"},
    "T1567": {"name": "Exfiltration Over Web Service", "tactic": "Exfiltration"},
    "T1567.001": {"name": "Exfiltration to Code Repository", "tactic": "Exfiltration", "parent": "T1567"},
    "T1567.002": {"name": "Exfiltration to Cloud Storage", "tactic": "Exfiltration", "parent": "T1567"},
    "T1567.003": {"name": "Exfiltration to Text Storage Sites", "tactic": "Exfiltration", "parent": "T1567"},
    "T1567.004": {"name": "Exfiltration Over Webhook", "tactic": "Exfiltration", "parent": "T1567"},
    "T1029": {"name": "Scheduled Transfer", "tactic": "Exfiltration"},
    "T1537": {"name": "Transfer Data to Cloud Account", "tactic": "Exfiltration"},

    # Impact
    "T1531": {"name": "Account Access Removal", "tactic": "Impact"},
    "T1485": {"name": "Data Destruction", "tactic": "Impact"},
    "T1486": {"name": "Data Encrypted for Impact", "tactic": "Impact"},
    "T1565": {"name": "Data Manipulation", "tactic": "Impact"},
    "T1565.001": {"name": "Stored Data Manipulation", "tactic": "Impact", "parent": "T1565"},
    "T1565.002": {"name": "Transmitted Data Manipulation", "tactic": "Impact", "parent": "T1565"},
    "T1565.003": {"name": "Runtime Data Manipulation", "tactic": "Impact", "parent": "T1565"},
    "T1491": {"name": "Defacement", "tactic": "Impact"},
    "T1491.001": {"name": "Internal Defacement", "tactic": "Impact", "parent": "T1491"},
    "T1491.002": {"name": "External Defacement", "tactic": "Impact", "parent": "T1491"},
    "T1561": {"name": "Disk Wipe", "tactic": "Impact"},
    "T1561.001": {"name": "Disk Content Wipe", "tactic": "Impact", "parent": "T1561"},
    "T1561.002": {"name": "Disk Structure Wipe", "tactic": "Impact", "parent": "T1561"},
    "T1499": {"name": "Endpoint Denial of Service", "tactic": "Impact"},
    "T1499.001": {"name": "OS Exhaustion Flood", "tactic": "Impact", "parent": "T1499"},
    "T1499.002": {"name": "Service Exhaustion Flood", "tactic": "Impact", "parent": "T1499"},
    "T1499.003": {"name": "Application Exhaustion Flood", "tactic": "Impact", "parent": "T1499"},
    "T1499.004": {"name": "Application or System Exploitation", "tactic": "Impact", "parent": "T1499"},
    "T1657": {"name": "Financial Theft", "tactic": "Impact"},
    "T1495": {"name": "Firmware Corruption", "tactic": "Impact"},
    "T1490": {"name": "Inhibit System Recovery", "tactic": "Impact"},
    "T1498": {"name": "Network Denial of Service", "tactic": "Impact"},
    "T1498.001": {"name": "Direct Network Flood", "tactic": "Impact", "parent": "T1498"},
    "T1498.002": {"name": "Reflection Amplification", "tactic": "Impact", "parent": "T1498"},
    "T1496": {"name": "Resource Hijacking", "tactic": "Impact"},
    "T1489": {"name": "Service Stop", "tactic": "Impact"},
    "T1529": {"name": "System Shutdown/Reboot", "tactic": "Impact"},
}


def get_technique_by_id(technique_id):
    """
    Get technique information by ID.

    Args:
        technique_id: MITRE ATT&CK technique ID (e.g., 'T1059' or 't1059')

    Returns:
        dict with technique info or None if not found
    """
    # Normalize ID to uppercase
    normalized_id = technique_id.upper()
    return TECHNIQUES.get(normalized_id)


def get_techniques_by_tactic(tactic):
    """
    Get all techniques for a given tactic.

    Args:
        tactic: MITRE ATT&CK tactic name

    Returns:
        dict of techniques for the tactic
    """
    return {
        tid: info for tid, info in TECHNIQUES.items()
        if info.get("tactic") == tactic
    }


def get_all_tactics():
    """Get list of all unique tactics."""
    tactics = set()
    for info in TECHNIQUES.values():
        tactics.add(info.get("tactic"))
    return sorted(list(tactics))


def get_parent_techniques():
    """Get only parent techniques (not sub-techniques)."""
    return {
        tid: info for tid, info in TECHNIQUES.items()
        if "parent" not in info
    }


def get_sub_techniques(parent_id):
    """Get sub-techniques for a given parent technique ID."""
    normalized_parent = parent_id.upper()
    return {
        tid: info for tid, info in TECHNIQUES.items()
        if info.get("parent") == normalized_parent
    }
